#!/usr/bin/env python


"""
Reference:
https://www.w3schools.com/python/python_datetime.asp
https://www.geeksforgeeks.org/python/generating-random-ids-using-uuid-python/
https://www.geeksforgeeks.org/python/how-to-add-and-subtract-days-using-datetime-in-python/
https://www.geeksforgeeks.org/python/python-program-to-find-number-of-days-between-two-given-dates/
https://www.geeksforgeeks.org/python/sort-a-list-of-objects-by-multiple-attributes-in-python/
"""

import argparse
import pickle
import datetime
import uuid
import tabulate
from tzlocal import get_localzone

class Task:
    """Representation of a task
    Attributes:
              - name - string
              - priority - int value of 1, 2, or 3; 1 is default, and 3 being highest
              - unique id - number (time hash, keep track of #) uuid python package
              - created - date  (python built-in modules)
              - completed - date (time-stamp)
              - due date - date, this is optional
    """
    #list of unique ids, and check with using a set
    unique_ids=set()

    #initializing task object
    def __init__(self,name,priority):
     self.name = name
     self.priority = priority
     self.unique_id = uuid.uuid1()
     while self.unique_id in Task.unique_ids:
         self.unique_id = uuid.uuid1()
     #grab timezone info of the user
     self.local_timezone = get_localzone()
     self.created_time = datetime.datetime.now()
     self.created_new = self.created_time.replace(tzinfo=self.local_timezone)
     self.created = self.created_new.strftime("%a %b %d %X %Z %Y")
     self.completed = False
     self.due_date = None
    
class Tasks:
    """A list of `Task` objects."""

    def __init__(self):
        """Read pickled tasks file into a list"""
        # when the program is run first time, check if pickle file exists, 
        # if there is no pickle file, we create one.
        try:
            with open('.todo.pickle','rb') as f:
                self.tasks = pickle.load(f)
        except:
            #if there is no existing pickle file, we initialize the list
            self.tasks = []
    
    def sort_list(self):
        """
        this function sorts the list according to due_date, and then priority using a tuple
        if due_date does not exists, return a max date to have them at the bottom of the list
        """
        self.tasks.sort(key=lambda x: (x.due_date if x.due_date is not None else "13/31/9999", x.priority))

    def pickle_tasks(self):
        """Picle your task list to a file
           This will be run everytime before program closes
        """
        #sort the list before saving it
        self.sort_list()
        #last thing that happens before program closes
        with open('.todo.pickle', 'wb') as f:
            pickle.dump(self.tasks, f)

    def list(self):
        """
        ID   Age  Due Date   Priority   Task
        --   ---  --------   --------   ----
        3    1d   -           2         Buy eggs
        4    30d  -           1         Make eggs
        """
        
        #display a list of not completed tasks sorted by due date. If same date, sort by decreasing priority
        data=[]
        current_time=datetime.datetime.now()
        self.sort_list()

        for i in self.tasks:
            if i.completed == False:
                 #calculate the age of task by calculating the difference between current time and instance's created data
                dif = current_time-i.created_time
                days_passed = f"{dif.days}d"
                data.append([i.unique_id,days_passed,i.due_date, i.priority, i.name])
             
        #print the data in simple table with headers
        print(tabulate.tabulate(data, headers=["ID", "Age", "Due Date", "Priority", "Task"], tablefmt="simple"))

    def report(self):
        """display all the tasks in below format:
        ID   Age  Due Date   Priority   Task      Created                       Completed
        --   ---  --------   --------   ----    ---------------------------   -------------------------
        """
        #add data into a nested list form
        data=[]
        current_time=datetime.datetime.now()
        for i in self.tasks:
            #calculate the age of task by calculating the difference between current time and instance's created data
            dif = current_time-i.created_time
            days_passed = f"{dif.days}d"
            data.append([i.unique_id,days_passed,i.due_date, i.priority, i.name, i.created, i.completed])
        #print the data in simple table with headers
        print(tabulate.tabulate(data, headers=["ID", "Age", "Due Date", "Priority", "Task", "Created", "Completed"], tablefmt="simple"))

    def done(self,id_string):
        #marking it as complete with the unique identifier
        for i in self.tasks:
            #unique_id is in uuid.UUID type, so convert it to string and compare to id entered by user and remove when matched
            if str(i.unique_id) == id_string:
                i.completed = True
                print(f"Completed task {id_string}")

    def query(self, query_string):
        data=[]
        current_time=datetime.datetime.now()
        #loop through each item 
        for i in self.tasks:
            #loop through keywords to find a match
            for item in query_string:
                if item.lower() in i.name.lower():
                    #print(i.name) 
                    dif = current_time-i.created_time
                    days_passed = f"{dif.days}d"
                    data.append([i.unique_id,days_passed,i.due_date, i.priority, i.name])
             
        #print the data in simple table with headers
        print(tabulate.tabulate(data, headers=["ID", "Age", "Due Date", "Priority", "Task"], tablefmt="simple"))


    def add(self,item):
        #add a new task
        self.tasks.append(item)
        #print(self.tasks)

    def delete(self,id_string):
        #delte the task with the unique identifier
        for i in self.tasks:
            #unique_id is in uuid.UUID type, so convert it to string and compare to id entered by user and remove when matched
            if str(i.unique_id) == id_string:
                self.tasks.remove(i)
                print(f"Deleted task {id_string}")

def main():
    #parsing the arguments passed by the user
    """
    ex) --add "Walk Dog" --due 4/17/2018 --priority 1
        --add "Study for finals" --due 3/20/2018 --priority 3
        --list
        --query eggs
        --done 1
        --delete 3
        --report
    """
    parser = argparse.ArgumentParser(description = "Update your ToDo List")
    parser.add_argument('--add', type=str, required = False, help = 'content of the task, etner string to add your list')
    parser.add_argument('--priority', type=int, required =False, default =1, help = "priority of task; default value is 1")
    parser.add_argument('--due', type = str, required=False, help="due date in dd/MM/YYY format")
    parser.add_argument('--query', type=str, required=False, nargs ="+", help="task details")
    parser.add_argument('--list', action = 'store_true', required = False, help="list all the tasks that have not been completed.")
    parser.add_argument('--report', action = 'store_true', required = False, help="list all the tasks both completed and incompleted.")
    parser.add_argument('--delete', type=str, required = False, help = 'enter id of the task you want to delete')
    parser.add_argument('--done', type=str, required = False, help = 'enter id of the task you want to mark it done')
    
    #parse the argument
    args = parser.parse_args()

    #Create instance of Tasks
    task_list = Tasks()


    #Read out arguments (note the types) + manipulate tasks

    if args.add:
        #task_list.add(args.add, args.priority)
        current_task=Task(args.add,args.priority)
        if args.due:
            try:
                #convert string to datetime format to check if it's in the right format
                new_date = datetime.datetime.strptime(args.due, "%m/%d/%Y").date()
                #convert back to string to save it in instance
                date_input = new_date.strftime("%m/%d/%Y")
                current_task.due_date = date_input

            except ValueError:
                print("Please enter a date with format MM/dd/YYYY.")
            
        #print(current_task.name, current_task.priority, current_task.created, current_task.unique_id, current_task.due_date)
        task_list.add(current_task)
        task_list.pickle_tasks()

    elif args.report:
        #print out all the tasks regardless of it being closed or not
        task_list.report()
    
    elif args.list:
        #print out the non-closed tasks
        task_list.list()
    
    elif args.delete:
        #user pass unique id of the task, and delete it from the existing list
        task_list.delete(args.delete)
        task_list.pickle_tasks()

    elif args.done:
        #user pass unique id and mark task as completed
        task_list.done(args.done)
        task_list.pickle_tasks()
    
    elif args.query:
        task_list.query(args.query)

#    for t in task_list.tasks():
 #       print("These are all the tasks in my Tasks() object")

    #to do something with the data based on the user commands
  #  task_list.pickle_tasks()
    exit

if __name__ == "__main__":
    main()
